public class EmailMessageConstants {
    public static final String CASE_STATUS_NEW = 'New';
    public static final String CASE_STATUS_OPEN = 'Open';
    public static final String CASE_STATUS_ASSIGNED = 'Assigned';
    public static final String CASE_STATUS_IN_PROGRESS = 'In Progress';
    public static final String CASE_STATUS_RESOLVED = 'Resolved';
    public static final String CASE_STATUS_CLOSED = 'Closed';
    public static final String CASE_STATUS_DUPLICATE = 'Duplicate';
    public static final String CASE_STATUS_SPAM = 'Spam';
    public static final String CASE_STATUS_REOPEN = 'Reopen';
    public static final String CASE_STATUS_DUP_NO_ACTION = 'DUP - No Action';
    public static final String CASE_STATUS_CLOSED_NO_ACTION = 'closed - No Action';
    public static final String CASE_STATUS_CLOSED_ABANDONED = 'Closed - Abandoned';
}