public class SOI_Constants {
    public static final String INNOVATION_TYPE = 'Innovation';
    public static final String STATUS_ACTIVE = 'Active';
    public static final String COUNTRY_USA = 'USA';
    public static final String SOI_REPORT_DEVELOPER_NAME = 'SOI_Project_Report_RYp';
    public static final String BEAM_SUNTORY_CUSTOMER_COMMUNITY = 'Beam_Suntory_Customer_Community_C';
    public static final String RED_BORDER = 'RedBorder';
    public static final String BLUE_BORDER = 'BlueBorder';
    public static final String STATE_AR = 'AR';
}